### ISSUE TITLE
"Please close game before proceeding"

### ISSUE THREAD

**Issue by dhdfw7** [WakuWakuPadoru/WuWa_Simple_FPSUnlocker#11]
As the title says, it thinks that my game is running when I try to click browse, but it's not. I even checked task manager, I am for sure not running the game

**Comment by WakuWakuPadoru** [comment]
> As the title says, it thinks that my game is running when I try to click browse, but it's not. I even checked task manager, I am for sure not running the game

Check your bottom right hand corner. There might be a WuWa icon there since the launcher itself also has to be closed.

**Comment by dhdfw7** [comment]
Yeah I already did that and made sure the launcher wasn't open

**Comment by WakuWakuPadoru** [comment]
![image](https://github.com/WakuWakuPadoru/WuWa_Simple_FPSUnlocker/assets/43870529/bc53a3c0-48f1-42cb-af47-7ec3867e1243)

In the search box above, make sure that the following aren't running:
- launcher.exe
- Wuthering Waves.exe

**Comment by dhdfw7** [comment]
Ah, so anything named launcher can't be open either even if it's not WuWa's I see. Thanks!

**Comment by WakuWakuPadoru** [comment]
I'll probably make this clearer, thanks on your part too!
