### ISSUE TITLE
Report of a error message

### ISSUE THREAD

**Issue by LynKen** [WakuWakuPadoru/WuWa_Simple_FPSUnlocker#5]
![image2](https://github.com/WakuWakuPadoru/WuWa_Simple_FPSUnlocker/assets/24799367/531d140a-01a6-4173-b321-c649d7340c4d)

Hello! I get this error message everytime I complete the setup of the fps unlocker. It seems to be working fine but still I think it could help reporting it.

Ty very much for the fps unlocker it is amazing!

Update: Running the fps unlocker as admin seems to resolve this error popup lol.. Srry for the trouble

**Comment by WakuWakuPadoru** [comment]
Thanks for the notice! Can I know where the game is installed at? The directory I mean.
